/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class TelaCadastroMoveis extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroMoveis
     */
    public TelaCadastroMoveis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanelCadastroMoveis1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NomeMovelCadastro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoPrecoCadastro = new javax.swing.JTextField();
        campoPesoCadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tamanhoEnvioCadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtdMaterialCadastro1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        plataformaCadastro1 = new javax.swing.JTextField();
        botaoAdicionaPlataforma = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        salvarcadMov = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        jLabel1.setText("Móvel");

        jLabel2.setText("Preço");

        jLabel3.setText("Tamanho Para Envio");

        tamanhoEnvioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanhoEnvioCadastroActionPerformed(evt);
            }
        });

        jLabel4.setText("Peso");

        jLabel5.setText("Material");

        qtdMaterialCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdMaterialCadastro1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Qtd");

        jLabel7.setText("Plataforma");

        botaoAdicionaPlataforma.setText("Adicionar outra");

        jButton1.setText("Adiciona Outro");

        salvarcadMov.setText("Salvar");
        salvarcadMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarcadMovActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroMoveis1Layout = new javax.swing.GroupLayout(jPanelCadastroMoveis1);
        jPanelCadastroMoveis1.setLayout(jPanelCadastroMoveis1Layout);
        jPanelCadastroMoveis1Layout.setHorizontalGroup(
            jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(NomeMovelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7))
                    .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                        .addComponent(campoPrecoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plataformaCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAdicionaPlataforma))
                    .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                            .addComponent(tamanhoEnvioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoPesoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroMoveis1Layout.createSequentialGroup()
                            .addComponent(qtdMaterialCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(salvarcadMov)
                                .addComponent(jButton1))))
                    .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 136, Short.MAX_VALUE))
        );
        jPanelCadastroMoveis1Layout.setVerticalGroup(
            jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroMoveis1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeMovelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPrecoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plataformaCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionaPlataforma))
                .addGap(17, 17, 17)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanhoEnvioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPesoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroMoveis1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdMaterialCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(salvarcadMov)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroMoveis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroMoveis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtdMaterialCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdMaterialCadastro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdMaterialCadastro1ActionPerformed

    private void tamanhoEnvioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanhoEnvioCadastroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tamanhoEnvioCadastroActionPerformed

    private void salvarcadMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarcadMovActionPerformed
        // TODO add your handling code here:
        variaveisCadastro();
    }//GEN-LAST:event_salvarcadMovActionPerformed
    public void variaveisCadastro(){
        String nomeMovelCad= NomeMovelCadastro.getText();
        JOptionPane.showMessageDialog(null, nomeMovelCad);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeMovelCadastro;
    private javax.swing.JButton botaoAdicionaPlataforma;
    private javax.swing.JTextField campoPesoCadastro;
    private javax.swing.JTextField campoPrecoCadastro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    javax.swing.JPanel jPanelCadastroMoveis1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField plataformaCadastro1;
    private javax.swing.JTextField qtdMaterialCadastro1;
    private javax.swing.JButton salvarcadMov;
    private javax.swing.JTextField tamanhoEnvioCadastro;
    // End of variables declaration//GEN-END:variables
}
